"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {Bell,Bookmark,BookmarkCheck,CheckCircle2,ChevronDown,Clock3,ExternalLink,ListFilter,LocateFixed,Map as MapIcon,MapPin,Menu,Search,ShieldCheck,SlidersHorizontal,Sparkles,X,Zap} from "lucide-react";
type Source="Facebook"|"Nextdoor"|"Craigslist"|"Direct"|"Public web";
type Lead={id:string;source:Source;title:string;excerpt:string;city:string;county:string;lat?:number;lng?:number;price?:number;postedAt:string;url:string;verified:boolean};
const DAY=864e5;
// Only verified direct submissions and authorized integrations may populate this feed.
const data:Lead[]=[];
const emoji:Record<Source,string>={Facebook:"📘",Nextdoor:"🏘️",Craigslist:"🟣",Direct:"📥","Public web":"🌐"};
const age=(s:string)=>{const h=Math.max(1,Math.floor((Date.now()-new Date(s).getTime())/36e5));return h<24?`${h}h ago`:`${Math.floor(h/24)}d ago`};
export default function App(){
 const[q,setQ]=useState(""),[source,setSource]=useState("All sources"),[tab,setTab]=useState<"map"|"list"|"saved">("map"),[selected,setSelected]=useState(""),[saved,setSaved]=useState<string[]>([]),[mobile,setMobile]=useState(false),[notice,setNotice]=useState("");
 useEffect(()=>{try{setSaved(JSON.parse(localStorage.getItem("mowlocal-saved")||"[]"))}catch{}},[]);
 const toggle=(id:string)=>setSaved(v=>{const n=v.includes(id)?v.filter(x=>x!==id):[...v,id];localStorage.setItem("mowlocal-saved",JSON.stringify(n));return n});
 const fresh=useMemo(()=>data.filter(l=>Date.now()-new Date(l.postedAt).getTime()<=20*DAY),[]);
 const leads=useMemo(()=>fresh.filter(l=>`${l.title} ${l.city} ${l.county} ${l.excerpt}`.toLowerCase().includes(q.toLowerCase())&&(source==="All sources"||l.source===source)&&(tab!=="saved"||saved.includes(l.id))),[fresh,q,source,tab,saved]);
 const mapped=leads.filter(l=>l.lat&&l.lng),missing=leads.filter(l=>!l.lat||!l.lng),pick=fresh.find(l=>l.id===selected);
 useEffect(()=>{if(leads.length&&!leads.some(l=>l.id===selected))setSelected(leads[0].id)},[leads,selected]);
 return <main><header className="topbar"><button className="mobile" onClick={()=>setMobile(!mobile)}><Menu/></button><a className="brand" href="#top"><Logo/><span>MowLocal <b>Leads</b></span><em>NC</em></a><nav className={mobile?"open":""}><button className={tab==="map"?"active":""} onClick={()=>setTab("map")}>🗺️ Lead Map</button><button className={tab==="list"?"active":""} onClick={()=>setTab("list")}>📋 All Leads</button><button className={tab==="saved"?"active":""} onClick={()=>setTab("saved")}>🔖 Saved <i>{saved.length}</i></button></nav><div className="tools"><button><Bell/></button><button className="pro"><Sparkles/> PRO</button><span>DW</span></div></header>
 <section className="hero" id="top"><div><small>● LIVE LEAD RADAR · NORTH CAROLINA</small><h1>Find lawns. <em>Win the work.</em> 🌱</h1><p>One clean feed for fresh mowing requests—organized by place, price, and source.</p></div><aside><Clock3/><span><b>Last 20 days only</b><small>Older leads hide automatically</small></span><CheckCircle2/></aside></section>
 <section className="search"><label><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search city, county, ZIP, or service…"/>{q&&<button onClick={()=>setQ("")}><X/></button>}</label><select value={source} onChange={e=>setSource(e.target.value)}>{["All sources","Direct","Public web","Craigslist","Facebook","Nextdoor"].map(x=><option key={x}>{x}</option>)}</select><select><option>Statewide NC</option><option>Within 25 miles</option><option>Within 50 miles</option></select><button className="filter"><SlidersHorizontal/> Filters <i>2</i></button></section>
 <section className="pulse"><div><span>⚡</span><p><b>{fresh.length} verified opportunities</b><small>{fresh.length?`Across ${new Set(fresh.map(x=>x.county)).size} NC counties · updated just now`:"Waiting for a verified source connection"}</small></p></div><div><small>Sources:</small>{(["Direct","Public web","Craigslist","Facebook","Nextdoor"] as Source[]).map(s=><i key={s}>{emoji[s]}</i>)}<button onClick={()=>document.getElementById("sources")?.scrollIntoView()}>Manage sources <ChevronDown/></button></div></section>
 {notice&&<div className="toast"><CheckCircle2/>{notice}<button onClick={()=>setNotice("")}><X/></button></div>}
 <section className={`workspace ${tab!=="map"?"listmode":""}`}><aside className="feed"><div className="feedhead"><span><b>{tab==="saved"?"Saved leads":`${leads.length} verified leads`}</b><small>Newest first · last 20 days</small></span><button><ListFilter/></button></div><div className="cards">{leads.length?leads.map(l=><Card key={l.id} lead={l} active={l.id===selected} saved={saved.includes(l.id)} select={()=>setSelected(l.id)} save={()=>toggle(l.id)}/>):<div className="empty">🌾<h3>No verified leads yet</h3><p>Connect an authorized source or import real leads you own.</p></div>}</div></aside>
 <section className="map"><LeadMap leads={mapped} selected={selected} select={setSelected}/><div className="maptop"><span>● {mapped.length} MAPPED LEADS</span><button><LocateFixed/> Use my location</button></div>{pick?.lat&&<div className="mapcard"><button onClick={()=>setSelected("")}><X/></button><small>{emoji[pick.source]} {pick.source}</small><h3>{pick.title}</h3><p><MapPin/> {pick.city}, {pick.county} County</p><div><strong>{pick.price?`$${pick.price}`:"Ask"}</strong><a href={pick.url} target="_blank">Ask now <ExternalLink/></a></div></div>}</section>
 <aside className="side"><header>📍 <span><b>Location needed</b><small>{missing.length} leads without a pin</small></span></header>{missing.map(l=><article key={l.id}><div><span>{emoji[l.source]}</span><small>{age(l.postedAt)}</small></div><b>{l.title}</b><p>{l.city}, NC · Address not posted</p><a href={l.url} target="_blank">Ask for location <ExternalLink/></a></article>)}<div className="alert"><Zap/><span><b>New-lead alerts</b><p>Get notified when a fresh lead appears nearby.</p><button onClick={()=>setNotice("Alerts are ready for setup 🔔")}>Set up alerts</button></span></div></aside></section>
 <section className="sources" id="sources"><div><small>🔌 SOURCE CENTER</small><h2>Bring every permitted lead into one place.</h2><p>MowLocal shows sources you connect and public posts that permit indexing. Private groups and restricted platforms require approved access.</p></div><div className="grid"><Connector e="📥" n="Direct requests" s="Ready" t="Connect customer submissions"/><Connector e="🌐" n="Public web" s="Connect" t="Add permitted public feeds"/><Connector e="📄" n="CSV / JSON import" s="Ready" t="Import leads you own" click={()=>setNotice("Importer ready for your authorized lead file 📄")}/><Connector e="📘" n="Facebook" s="Approval needed" t="Requires Meta-approved access"/><Connector e="🏘️" n="Nextdoor" s="Approval needed" t="Requires partner access"/><Connector e="🟣" n="Craigslist" s="Connect" t="Use permitted feed or links"/></div></section>
 <footer><a className="brand" href="#top"><Logo/><span>MowLocal <b>Leads</b></span></a><p>Built for lawn pros across North Carolina. 🌱</p><span><ShieldCheck/> Public and authorized sources only</span></footer></main>}
function Card({lead,active,saved,select,save}:{lead:Lead;active:boolean;saved:boolean;select:()=>void;save:()=>void}){return <article className={`card ${active?"active":""}`} onClick={select}><div className="cardtop"><small>{emoji[lead.source]} {lead.source}</small><span><Clock3/> {age(lead.postedAt)}</span><button onClick={e=>{e.stopPropagation();save()}}>{saved?<BookmarkCheck/>:<Bookmark/>}</button></div><h3>{lead.title}</h3><p>{lead.excerpt}</p><div className="where"><MapPin/><span><b>{lead.city}</b><small>{lead.county} County, NC</small></span>{lead.price&&<strong>${lead.price}</strong>}</div><div className="actions"><span>{lead.verified?"✅ Location verified":"⚠️ Location approximate"}</span><a href={lead.url} target="_blank" onClick={e=>e.stopPropagation()}>Ask now <ExternalLink/></a></div></article>}
function Connector({e,n,s,t,click}:{e:string;n:string;s:string;t:string;click?:()=>void}){return <article><span>{e}</span><div><b>{n}</b><small>{t}</small></div><button className={s==="Live"?"live":""} onClick={click}>{s==="Live"?"● Live":s}</button></article>}
function Logo(){return <svg className="logo" viewBox="0 0 48 58"><path d="M24 56S3 34 3 21C3 10 12 2 24 2s21 8 21 19c0 13-21 35-21 35Z" fill="#176b43"/><circle cx="24" cy="21" r="14" fill="#bcebd1"/><path d="M24 31V14M24 26c-6-2-9-6-10-11 6 1 10 4 10 11Zm0-5c5-2 8-6 9-11-5 1-8 5-9 11Zm0-7C22 8 24 4 27 1c2 6 1 10-3 13Z" fill="none" stroke="#fff" strokeWidth="3.2" strokeLinecap="round"/></svg>}
function LeadMap({leads,selected,select}:{leads:Lead[];selected:string;select:(x:string)=>void}){const el=useRef<HTMLDivElement>(null),map=useRef<any>(null),tiles=useRef<any>(null),marks=useRef<any[]>([]);const[style,setStyle]=useState<"satellite"|"street">("satellite");useEffect(()=>{const init=()=>{const L=(window as any).L;if(!L||!el.current||map.current)return;map.current=L.map(el.current,{zoomControl:false}).setView([35.45,-79.3],7);L.control.zoom({position:"bottomright"}).addTo(map.current);setStyle(x=>x)};if((window as any).L)init();else{if(!document.querySelector("link[data-leaflet]")){const c=document.createElement("link");c.rel="stylesheet";c.href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css";c.dataset.leaflet="1";document.head.appendChild(c)}let s=document.querySelector("script[data-leaflet]") as HTMLScriptElement|null;if(!s){s=document.createElement("script");s.src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js";s.dataset.leaflet="1";document.body.appendChild(s)}s.addEventListener("load",init,{once:true})}},[]);useEffect(()=>{const L=(window as any).L;if(!L||!map.current)return;if(tiles.current)map.current.removeLayer(tiles.current);const url=style==="satellite"?"https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}":"https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png";tiles.current=L.tileLayer(url,{maxZoom:19,attribution:style==="satellite"?"© Esri":"© OpenStreetMap"}).addTo(map.current)},[style,map.current]);useEffect(()=>{const L=(window as any).L;if(!L||!map.current)return;marks.current.forEach(m=>m.remove());marks.current=leads.map(l=>{const icon=L.divIcon({className:"markerbox",html:`<button class="marker ${selected===l.id?'chosen':''}">${l.price?'$'+l.price:'🌱'}</button>`,iconSize:[54,38],iconAnchor:[27,38]});const m=L.marker([l.lat,l.lng],{icon}).addTo(map.current);m.on("click",()=>select(l.id));return m})},[leads,selected,select,map.current]);return <><div ref={el} className="leafletmap"/><div className="layers"><button className={style==="satellite"?"active":""} onClick={()=>setStyle("satellite")}>🛰️ Satellite</button><button className={style==="street"?"active":""} onClick={()=>setStyle("street")}><MapIcon/> Street</button></div></>}
